version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app:/django_file_processing/
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

volumes:
  app:
