version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8080:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
