# Generated by Django 4.2.3 on 2023-07-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Record name')),
                ('level', models.IntegerField(choices=[(0, 'NOT SET'), (10, 'DEBUG'), (20, 'INFO'), (30, 'WARNING'), (40, 'ERROR'), (50, 'CRITICAL')], verbose_name='Log level')),
                ('message', models.TextField(blank=True, null=True)),
                ('timedate', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
        ),
    ]
