# Generated by Django 4.2.3 on 2023-07-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecord',
            name='message',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='logrecord',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Record name'),
        ),
    ]
