# Generated by Django 4.2.3 on 2023-07-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_record', '0002_alter_logrecord_message_alter_logrecord_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecord',
            name='level',
            field=models.IntegerField(choices=[(0, 'NOT SET'), (10, 'DEBUG'), (20, 'INFO'), (30, 'WARNING'), (40, 'ERROR'), (50, 'CRITICAL')], editable=False, verbose_name='Log level'),
        ),
        migrations.AlterField(
            model_name='logrecord',
            name='message',
            field=models.CharField(blank=True, editable=False, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='logrecord',
            name='name',
            field=models.CharField(editable=False, max_length=64, verbose_name='Record name'),
        ),
    ]
