IMAGE_INPUT_FORMATS = {
    "blp": "Blizzard Texture Format",
    "bmp": "Bitmap",
    "bufr": "Binary Universal Form for the Representation of meteorological data",
    "cur": "Cursor",
    "dcx": "ZSoft IBM PC multi-page Paintbrush image",
    "dds": "DirectDraw Surface",
    "dib": "Device Independent Bitmap",
    "eps": "Encapsulated PostScript",
    "ps": "PostScript",
    "fit": "FITS (Flexible Image Transport System)",
    "fits": "FITS (Flexible Image Transport System)",
    "flc": "FLIC Animation",
    "fli": "FLIC Animation",
    "gbr": "GIMP Brush",
    "grib": "GRIdded Binary or General Regularly-distributed Information in Binary form",
    "h5": "Hierarchical Data Format 5",
    "hdf": "Hierarchical Data Format",
    "icns": "Apple Icon Image format",
    "ico": "Icon format",
    "im": "ImageMagick Script",
    "imt": "ImageMagick Textual image",
    "iim": "IPTC Image Metadata",
    "jfif": "JPEG File Interchange Format",
    "jpe": "JPEG Image",
    "jpeg": "Joint Photographic Experts Group",
    "jpg": "JPEG Image",
    "j2c": "JPEG 2000 Code Stream",
    "j2k": "JPEG 2000 Image",
    "jp2": "JPEG 2000 Core Image File",
    "jpc": "JPEG 2000 Code Stream",
    "jpf": "JPEG 2000 File Format",
    "jpx": "JPEG 2000 Part 2",
    "msp": "Microsoft Paint",
    "pcd": "Photo CD",
    "pcx": "PiCture eXchange",
    "pxr": "Pixar Picture File",
    "apng": "Animated Portable Network Graphics",
    "png": "Portable Network Graphics",
    "pbm": "Portable Bitmap",
    "pgm": "Portable Graymap",
    "pnm": "Portable aNy Map",
    "ppm": "Portable Pixmap",
    "psd": "Adobe Photoshop Document",
    "qoi": "Quake 2 Image",
    "bw": "SGI Black and White",
    "rgb": "SGI RGB Image",
    "rgba": "SGI RGB Image with Alpha Channel",
    "sgi": "Silicon Graphics Image",
    "ras": "Sun Raster Image",
    "icb": "Truevision Targa Image",
    "tga": "Truevision TGA Image",
    "vda": "Truevision Targa Image",
    "vst": "Truevision Targa Image",
    "tif": "Tagged Image File Format",
    "tiff": "Tagged Image File Format",
    "webp": "WebP image",
    "emf": "Windows Enhanced Metafile",
    "wmf": "Windows Metafile",
    "xbm": "X BitMap",
    "xpm": "X PixMap",
}

IMAGE_OUTPUT_FORMATS = {
    "blp": "Blizzard Texture Format",
    "bmp": "Bitmap",
    "bufr": "Binary Universal Form for the Representation of meteorological data",
    "dds": "DirectDraw Surface",
    "dib": "Device Independent Bitmap",
    "eps": "Encapsulated PostScript",
    "ps": "PostScript",
    "grib": "GRIdded Binary or General Regularly-distributed Information in Binary form",
    "h5": "Hierarchical Data Format 5",
    "hdf": "Hierarchical Data Format",
    "icns": "Apple Icon Image format",
    "ico": "Icon format",
    "im": "ImageMagick Script",
    "imt": "ImageMagick Textual image",
    "jfif": "JPEG File Interchange Format",
    "jpe": "JPEG Image",
    "jpeg": "Joint Photographic Experts Group",
    "jpg": "JPEG Image",
    "j2c": "JPEG 2000 Code Stream",
    "j2k": "JPEG 2000 Image",
    "jp2": "JPEG 2000 Core Image File",
    "jpc": "JPEG 2000 Code Stream",
    "jpf": "JPEG 2000 File Format",
    "jpx": "JPEG 2000 Part 2",
    "msp": "Microsoft Paint",
    "pcx": "PiCture eXchange",
    "apng": "Animated Portable Network Graphics",
    "png": "Portable Network Graphics",
    "pbm": "Portable Bitmap",
    "pgm": "Portable Graymap",
    "pnm": "Portable aNy Map",
    "ppm": "Portable Pixmap",
    "bw": "SGI Black and White",
    "rgb": "SGI RGB Image",
    "rgba": "SGI RGB Image with Alpha Channel",
    "sgi": "Silicon Graphics Image",
    "icb": "Truevision Targa Image",
    "tga": "Truevision TGA Image",
    "vda": "Truevision Targa Image",
    "vst": "Truevision Targa Image",
    "tif": "Tagged Image File Format",
    "tiff": "Tagged Image File Format",
    "webp": "WebP image",
    "emf": "Windows Enhanced Metafile",
    "wmf": "Windows Metafile",
    "xbm": "X BitMap",
}

DOCUMENT_INPUT_FORMATS = {
    "bib": "bibtex",
    "md": "markdown",
    "creole": "creole",
    "csljson": "csljson",
    "csv": "csv",
    "xml": "docbook",
    "docx": "docx",
    "dokuwiki": "dokuwiki",
    "epub": "epub",
    "fb2": "fb2",
    "haddock": "haddock",
    "html": "html",
    "ipynb": "ipynb",
    "jats": "jats",
    "jira": "jira",
    "json": "json",
    "tex": "latex",
    "man": "man",
    "mediawiki": "mediawiki",
    "muse": "muse",
    "native": "native",
    "odt": "odt",
    "opml": "opml",
    "org": "org",
    "rst": "rst",
    "rtf": "rtf",
    "t2t": "t2t",
    "textile": "textile",
    "tikiwiki": "tikiwiki",
    "twiki": "twiki",
    "vimwiki": "vimwiki"
}

DOCUMENT_OUTPUT_FORMATS = {
    "bib": "bibtex",
    "md": "markdown_strict",
    "creole": "creole",
    "csljson": "csljson",
    "csv": "csv",
    "xml": "docbook",
    "docx": "docx",
    "dokuwiki": "dokuwiki",
    "epub": "epub",
    "fb2": "fb2",
    "haddock": "haddock",
    "html": "html",
    "ipynb": "ipynb",
    "jats": "jats",
    "jira": "jira",
    "json": "json",
    "tex": "latex",
    "man": "man",
    "mediawiki": "mediawiki",
    "muse": "muse",
    "native": "native",
    "odt": "odt",
    "opml": "opml",
    "org": "org",
    "rst": "rst",
    "rtf": "rtf",
    "t2t": "t2t",
    "textile": "textile",
    "tikiwiki": "tikiwiki",
    "twiki": "twiki",
    "vimwiki": "vimwiki",
    "asciidoc": "asciidoc",
    "asciidoctor": "asciidoctor",
    "beamer": "beamer",
    "context": "context",
    "docbook": "docbook",
    "docbook4": "docbook4",
    "docbook5": "docbook5",
    "dzslides": "dzslides",
    "epub2": "epub2",
    "epub3": "epub3",
    "icml": "icml",
    "markua": "markua",
    "ms": "ms",
    "odt": "opendocument",
    "pdf": "pdf",
    "txt": "plain",
    "pptx": "pptx",
    "revealjs": "revealjs",
    "s5": "s5",
    "slideous": "slideous",
    "slidy": "slidy",
    "tei": "tei",
    "texinfo": "texinfo",
    "xwiki": "xwiki",
    "zimwiki": "zimwiki"
}

VIDEO_INPUT_FORMATS = {
    "webm": "WebM video format",
    "mpg": "MPEG video format",
    "mp2": "MPEG-2 video format",
    "mpeg": "MPEG video format",
    "mpe": "MPEG video format",
    "mpv": "MPEG video format",
    "ogg": "Ogg video format",
    "mp4": "MPEG-4 video format",
    "m4p": "MPEG-4 protected video format",
    "m4v": "MPEG-4 video format",
    "avi": "Audio Video Interleave format",
    "wmv": "Windows Media Video format",
    "mov": "QuickTime video format",
    "qt": "QuickTime video format",
    "flv": "Flash Video format",
    "swf": "Shockwave Flash format",
    "avchd": "Advanced Video Coding High Definition format"
}
