# Generated by Django 4.2.3 on 2023-07-16 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the task', max_length=64, verbose_name='Name')),
                ('status', models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('finished', 'Finished'), ('errored', 'Errored'), ('canceled', 'Canceled')], default='created', help_text='Current state of the task', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(editable=False, help_text='Date that the task was create', verbose_name='Creation date')),
                ('closed_at', models.DateTimeField(blank=True, help_text='Date that the task was finished/errored', null=True, verbose_name='Closure date')),
                ('initiator', models.ForeignKey(help_text='User that initiated the task', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Task initiator')),
            ],
        ),
        migrations.CreateModel(
            name='MazeGenerationTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='task.task')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('algorithm', models.CharField(choices=[('Algorithms.BINARY_TREE', 'Binary Tree'), ('Algorithms.SIDEWINDER', 'Sidewinder'), ('Algorithms.ALDOUS_BRODER', 'Aldous Broder'), ('Algorithms.WILSON', 'Wilson'), ('Algorithms.HUNT_AND_KILL', 'Hunt And Kill'), ('Algorithms.RECURSIVE_BACKTRACKER', 'Recursive Backtracker')], default='Algorithms.BINARY_TREE', max_length=32)),
                ('result', models.ImageField(blank=True, null=True, upload_to='mazes')),
            ],
            bases=('task.task',),
        ),
    ]
