# Generated by Django 4.2.3 on 2023-07-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the task', max_length=64, verbose_name='Name')),
                ('status', models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('finished', 'Finished'), ('errored', 'Errored')], default='created', help_text='Current state of the task', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='Date that the task was create', verbose_name='Creation date')),
                ('closed_at', models.DateTimeField(blank=True, help_text='Date that the task was finished/errored', null=True, verbose_name='Closure date')),
            ],
        ),
    ]
