# Generated by Django 4.2.3 on 2023-07-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='mazegenerationtask',
            name='height',
        ),
        migrations.RemoveField(
            model_name='mazegenerationtask',
            name='width',
        ),
        migrations.AddField(
            model_name='mazegenerationtask',
            name='columns',
            field=models.IntegerField(default=75, help_text='Number of cells in a column', verbose_name='Columns'),
        ),
        migrations.AddField(
            model_name='mazegenerationtask',
            name='rows',
            field=models.IntegerField(default=75, help_text='Number of cells in a row', verbose_name='Rows'),
        ),
        migrations.AddField(
            model_name='mazegenerationtask',
            name='scale',
            field=models.IntegerField(default=4, help_text='Number of pixels per cell', verbose_name='Scale'),
        ),
        migrations.AlterField(
            model_name='mazegenerationtask',
            name='algorithm',
            field=models.CharField(choices=[('binary_tree', 'Binary Tree'), ('sidewinder', 'Sidewinder'), ('aldous_broder', 'Aldous Broder'), ('wilson', 'Wilson'), ('hunt_and_kill', 'Hunt And Kill'), ('recursive_backtracker', 'Recursive Backtracker')], default='binary_tree', help_text='Algorithm used for maze generation', max_length=32, verbose_name='Generation algorithm'),
        ),
        migrations.AlterField(
            model_name='mazegenerationtask',
            name='result',
            field=models.ImageField(blank=True, help_text='Result Image', null=True, upload_to='mazes', verbose_name='Result Image'),
        ),
    ]
