# Generated by Django 4.2.3 on 2023-08-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversiontask',
            name='output_format',
            field=models.CharField(choices=[('blp', 'Blizzard Texture Format'), ('bmp', 'Bitmap'), ('bufr', 'Binary Universal Form for the Representation of meteorological data'), ('dds', 'DirectDraw Surface'), ('dib', 'Device Independent Bitmap'), ('eps', 'Encapsulated PostScript'), ('ps', 'PostScript'), ('grib', 'GRIdded Binary or General Regularly-distributed Information in Binary form'), ('h5', 'Hierarchical Data Format 5'), ('hdf', 'Hierarchical Data Format'), ('icns', 'Apple Icon Image format'), ('ico', 'Icon format'), ('im', 'ImageMagick Script'), ('imt', 'ImageMagick Textual image'), ('jfif', 'JPEG File Interchange Format'), ('jpe', 'JPEG Image'), ('jpeg', 'Joint Photographic Experts Group'), ('jpg', 'JPEG Image'), ('j2c', 'JPEG 2000 Code Stream'), ('j2k', 'JPEG 2000 Image'), ('jp2', 'JPEG 2000 Core Image File'), ('jpc', 'JPEG 2000 Code Stream'), ('jpf', 'JPEG 2000 File Format'), ('jpx', 'JPEG 2000 Part 2'), ('msp', 'Microsoft Paint'), ('pcx', 'PiCture eXchange'), ('apng', 'Animated Portable Network Graphics'), ('png', 'Portable Network Graphics'), ('pbm', 'Portable Bitmap'), ('pgm', 'Portable Graymap'), ('pnm', 'Portable aNy Map'), ('ppm', 'Portable Pixmap'), ('bw', 'SGI Black and White'), ('rgb', 'SGI RGB Image'), ('rgba', 'SGI RGB Image with Alpha Channel'), ('sgi', 'Silicon Graphics Image'), ('icb', 'Truevision Targa Image'), ('tga', 'Truevision TGA Image'), ('vda', 'Truevision Targa Image'), ('vst', 'Truevision Targa Image'), ('tif', 'Tagged Image File Format'), ('tiff', 'Tagged Image File Format'), ('webp', 'WebP image'), ('emf', 'Windows Enhanced Metafile'), ('wmf', 'Windows Metafile'), ('xbm', 'X BitMap'), ('bib', 'bibtex'), ('md', 'markdown_strict'), ('creole', 'creole'), ('csljson', 'csljson'), ('csv', 'csv'), ('xml', 'docbook'), ('docx', 'docx'), ('dokuwiki', 'dokuwiki'), ('epub', 'epub'), ('fb2', 'fb2'), ('haddock', 'haddock'), ('html', 'html'), ('ipynb', 'ipynb'), ('jats', 'jats'), ('jira', 'jira'), ('json', 'json'), ('tex', 'latex'), ('man', 'man'), ('mediawiki', 'mediawiki'), ('muse', 'muse'), ('native', 'native'), ('odt', 'opendocument'), ('opml', 'opml'), ('org', 'org'), ('rst', 'rst'), ('rtf', 'rtf'), ('t2t', 't2t'), ('textile', 'textile'), ('tikiwiki', 'tikiwiki'), ('twiki', 'twiki'), ('vimwiki', 'vimwiki'), ('asciidoc', 'asciidoc'), ('asciidoctor', 'asciidoctor'), ('beamer', 'beamer'), ('context', 'context'), ('docbook', 'docbook'), ('docbook4', 'docbook4'), ('docbook5', 'docbook5'), ('dzslides', 'dzslides'), ('epub2', 'epub2'), ('epub3', 'epub3'), ('icml', 'icml'), ('markua', 'markua'), ('ms', 'ms'), ('pdf', 'pdf'), ('txt', 'plain'), ('pptx', 'pptx'), ('revealjs', 'revealjs'), ('s5', 's5'), ('slideous', 'slideous'), ('slidy', 'slidy'), ('tei', 'tei'), ('texinfo', 'texinfo'), ('xwiki', 'xwiki'), ('zimwiki', 'zimwiki')], max_length=12),
        ),
    ]
