# Generated by Django 4.2.3 on 2023-07-27 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_options_delete_mazegenerationtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='task.task')),
                ('input_file', models.FileField(help_text='Input File', upload_to='inputs', verbose_name='Input File')),
                ('output_file', models.FileField(blank=True, help_text='Output File', null=True, upload_to='outputs', verbose_name='Output File')),
            ],
            bases=('task.task',),
        ),
        migrations.CreateModel(
            name='DocumentConversionTask',
            fields=[
                ('conversiontask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='task.conversiontask')),
                ('input_format', models.CharField(choices=[('0', 'biblatex'), ('1', 'bibtex'), ('2', 'commonmark'), ('3', 'commonmark_x'), ('4', 'creole'), ('5', 'csljson'), ('6', 'csv'), ('7', 'docbook'), ('8', 'docx'), ('9', 'dokuwiki'), ('10', 'epub'), ('11', 'fb2'), ('12', 'gfm'), ('13', 'haddock'), ('14', 'html'), ('15', 'ipynb'), ('16', 'jats'), ('17', 'jira'), ('18', 'json'), ('19', 'latex'), ('20', 'man'), ('21', 'markdown'), ('22', 'markdown_github'), ('23', 'markdown_mmd'), ('24', 'markdown_phpextra'), ('25', 'markdown_strict'), ('26', 'mediawiki'), ('27', 'muse'), ('28', 'native'), ('29', 'odt'), ('30', 'opml'), ('31', 'org'), ('32', 'rst'), ('33', 'rtf'), ('34', 't2t'), ('35', 'textile'), ('36', 'tikiwiki'), ('37', 'twiki'), ('38', 'vimwiki')], max_length=3)),
                ('output_format', models.CharField(choices=[('0', 'asciidoc'), ('1', 'asciidoctor'), ('2', 'beamer'), ('3', 'biblatex'), ('4', 'bibtex'), ('5', 'commonmark'), ('6', 'commonmark_x'), ('7', 'context'), ('8', 'csljson'), ('9', 'docbook'), ('10', 'docbook4'), ('11', 'docbook5'), ('12', 'docx'), ('13', 'dokuwiki'), ('14', 'dzslides'), ('15', 'epub'), ('16', 'epub2'), ('17', 'epub3'), ('18', 'fb2'), ('19', 'gfm'), ('20', 'haddock'), ('21', 'html'), ('22', 'html4'), ('23', 'html5'), ('24', 'icml'), ('25', 'ipynb'), ('26', 'jats'), ('27', 'jats_archiving'), ('28', 'jats_articleauthoring'), ('29', 'jats_publishing'), ('30', 'jira'), ('31', 'json'), ('32', 'latex'), ('33', 'man'), ('34', 'markdown'), ('35', 'markdown_github'), ('36', 'markdown_mmd'), ('37', 'markdown_phpextra'), ('38', 'markdown_strict'), ('39', 'markua'), ('40', 'mediawiki'), ('41', 'ms'), ('42', 'muse'), ('43', 'native'), ('44', 'odt'), ('45', 'opendocument'), ('46', 'opml'), ('47', 'org'), ('48', 'pdf'), ('49', 'plain'), ('50', 'pptx'), ('51', 'revealjs'), ('52', 'rst'), ('53', 'rtf'), ('54', 's5'), ('55', 'slideous'), ('56', 'slidy'), ('57', 'tei'), ('58', 'texinfo'), ('59', 'textile'), ('60', 'xwiki'), ('61', 'zimwiki')], max_length=3)),
            ],
            bases=('task.conversiontask',),
        ),
    ]
