# Generated by Django 4.2.3 on 2023-08-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_conversiontask_output_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(help_text='Name of the task', max_length=64, verbose_name='Name'),
        ),
    ]
