# Generated by Django 4.2.3 on 2023-07-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(editable=False, help_text='Date that the task was create', verbose_name='Creation date'),
        ),
    ]
