# Generated by Django 4.2.3 on 2023-07-15 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0003_alter_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='initiator',
            field=models.ForeignKey(editable=False, help_text='User that initiated the task', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Task initiator'),
            preserve_default=False,
        ),
    ]
