# Generated by Django 4.2.3 on 2023-07-28 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0003_conversiontask_documentconversiontask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentconversiontask',
            name='input_format',
        ),
        migrations.AlterField(
            model_name='documentconversiontask',
            name='output_format',
            field=models.CharField(choices=[('asciidoc', 'asciidoc'), ('asciidoctor', 'asciidoctor'), ('beamer', 'beamer'), ('biblatex', 'biblatex'), ('bibtex', 'bibtex'), ('commonmark', 'commonmark'), ('commonmark_x', 'commonmark_x'), ('context', 'context'), ('csljson', 'csljson'), ('docbook', 'docbook'), ('docbook4', 'docbook4'), ('docbook5', 'docbook5'), ('docx', 'docx'), ('dokuwiki', 'dokuwiki'), ('dzslides', 'dzslides'), ('epub', 'epub'), ('epub2', 'epub2'), ('epub3', 'epub3'), ('fb2', 'fb2'), ('gfm', 'gfm'), ('haddock', 'haddock'), ('html', 'html'), ('html4', 'html4'), ('html5', 'html5'), ('icml', 'icml'), ('ipynb', 'ipynb'), ('jats', 'jats'), ('jats_archiving', 'jats_archiving'), ('jats_articleauthoring', 'jats_articleauthoring'), ('jats_publishing', 'jats_publishing'), ('jira', 'jira'), ('json', 'json'), ('latex', 'latex'), ('man', 'man'), ('markdown', 'markdown'), ('markdown_github', 'markdown_github'), ('markdown_mmd', 'markdown_mmd'), ('markdown_phpextra', 'markdown_phpextra'), ('markdown_strict', 'markdown_strict'), ('markua', 'markua'), ('mediawiki', 'mediawiki'), ('ms', 'ms'), ('muse', 'muse'), ('native', 'native'), ('odt', 'odt'), ('opendocument', 'opendocument'), ('opml', 'opml'), ('org', 'org'), ('pdf', 'pdf'), ('plain', 'plain'), ('pptx', 'pptx'), ('revealjs', 'revealjs'), ('rst', 'rst'), ('rtf', 'rtf'), ('s5', 's5'), ('slideous', 'slideous'), ('slidy', 'slidy'), ('tei', 'tei'), ('texinfo', 'texinfo'), ('textile', 'textile'), ('xwiki', 'xwiki'), ('zimwiki', 'zimwiki')], max_length=21),
        ),
        migrations.AlterField(
            model_name='task',
            name='initiator',
            field=models.ForeignKey(help_text='User that initiated the task', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Task initiator'),
        ),
    ]
