# Generated by Django 4.2.3 on 2023-10-13 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_upload_media_type'),
        ('task', '0004_alter_conversiontask_output_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversiontask',
            name='upload',
            field=models.ForeignKey(help_text='Uploaded file that needs conversion', on_delete=django.db.models.deletion.CASCADE, to='upload.upload', verbose_name='Uploaded file'),
        ),
        migrations.CreateModel(
            name='OCRTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='task.task')),
                ('language', models.CharField(choices=[('eng', 'English'), ('ukr', 'Ukrainian'), ('rus', 'Russian')], max_length=3)),
                ('output', models.TextField(blank=True, null=True)),
                ('upload', models.ForeignKey(help_text='Uploaded file that needs OCR', on_delete=django.db.models.deletion.CASCADE, to='upload.upload', verbose_name='Uploaded file')),
            ],
            bases=('task.task',),
        ),
    ]
