# Generated by Django 4.2.3 on 2023-07-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_initiator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('finished', 'Finished'), ('errored', 'Errored'), ('canceled', 'Canceled')], default='created', help_text='Current state of the task', max_length=10, verbose_name='Status'),
        ),
    ]
