# Generated by Django 4.2.3 on 2023-07-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_imageconversiontask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageconversiontask',
            name='quality',
            field=models.IntegerField(default=100),
        ),
    ]
