# Generated by Django 4.2.3 on 2023-08-25 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the upload', max_length=256, verbose_name='Name')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('other', 'Other')], default='other', help_text='Media type of the upload file', max_length=10, verbose_name='Media type')),
                ('file', models.FileField(help_text='Media file', upload_to='uploads', verbose_name='Media file')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date the upload was created at', verbose_name='Creation date')),
                ('user', models.ForeignKey(help_text='User that uploaded a upload', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
