INPUT_FORMATS = {
    "blp": "Blizzard Texture Format",
    "bmp": "Bitmap",
    "bufr": "Binary Universal Form for the Representation of meteorological data",
    "cur": "Cursor",
    "dcx": "ZSoft IBM PC multi-page Paintbrush image",
    "dds": "DirectDraw Surface",
    "dib": "Device Independent Bitmap",
    "eps": "Encapsulated PostScript",
    "ps": "PostScript",
    "fit": "FITS (Flexible Image Transport System)",
    "fits": "FITS (Flexible Image Transport System)",
    "flc": "FLIC Animation",
    "fli": "FLIC Animation",
    "gbr": "GIMP Brush",
    "grib": "GRIdded Binary or General Regularly-distributed Information in Binary form",
    "h5": "Hierarchical Data Format 5",
    "hdf": "Hierarchical Data Format",
    "icns": "Apple Icon Image format",
    "ico": "Icon format",
    "im": "ImageMagick Script",
    "imt": "ImageMagick Textual image",
    "iim": "IPTC Image Metadata",
    "jfif": "JPEG File Interchange Format",
    "jpe": "JPEG Image",
    "jpeg": "Joint Photographic Experts Group",
    "jpg": "JPEG Image",
    "j2c": "JPEG 2000 Code Stream",
    "j2k": "JPEG 2000 Image",
    "jp2": "JPEG 2000 Core Image File",
    "jpc": "JPEG 2000 Code Stream",
    "jpf": "JPEG 2000 File Format",
    "jpx": "JPEG 2000 Part 2",
    "msp": "Microsoft Paint",
    "pcd": "Photo CD",
    "pcx": "PiCture eXchange",
    "pxr": "Pixar Picture File",
    "apng": "Animated Portable Network Graphics",
    "png": "Portable Network Graphics",
    "pbm": "Portable Bitmap",
    "pgm": "Portable Graymap",
    "pnm": "Portable aNy Map",
    "ppm": "Portable Pixmap",
    "psd": "Adobe Photoshop Document",
    "qoi": "Quake 2 Image",
    "bw": "SGI Black and White",
    "rgb": "SGI RGB Image",
    "rgba": "SGI RGB Image with Alpha Channel",
    "sgi": "Silicon Graphics Image",
    "ras": "Sun Raster Image",
    "icb": "Truevision Targa Image",
    "tga": "Truevision TGA Image",
    "vda": "Truevision Targa Image",
    "vst": "Truevision Targa Image",
    "tif": "Tagged Image File Format",
    "tiff": "Tagged Image File Format",
    "webp": "WebP image",
    "emf": "Windows Enhanced Metafile",
    "wmf": "Windows Metafile",
    "xbm": "X BitMap",
    "xpm": "X PixMap",
}
INPUT_FORMATS_CHOICES = [(key, value) for key, value in INPUT_FORMATS.items()]

OUTPUT_FORMATS = {
    "blp": "Blizzard Texture Format",
    "bmp": "Bitmap",
    "bufr": "Binary Universal Form for the Representation of meteorological data",
    "dds": "DirectDraw Surface",
    "dib": "Device Independent Bitmap",
    "eps": "Encapsulated PostScript",
    "ps": "PostScript",
    "grib": "GRIdded Binary or General Regularly-distributed Information in Binary form",
    "h5": "Hierarchical Data Format 5",
    "hdf": "Hierarchical Data Format",
    "icns": "Apple Icon Image format",
    "ico": "Icon format",
    "im": "ImageMagick Script",
    "imt": "ImageMagick Textual image",
    "jfif": "JPEG File Interchange Format",
    "jpe": "JPEG Image",
    "jpeg": "Joint Photographic Experts Group",
    "jpg": "JPEG Image",
    "j2c": "JPEG 2000 Code Stream",
    "j2k": "JPEG 2000 Image",
    "jp2": "JPEG 2000 Core Image File",
    "jpc": "JPEG 2000 Code Stream",
    "jpf": "JPEG 2000 File Format",
    "jpx": "JPEG 2000 Part 2",
    "msp": "Microsoft Paint",
    "pcx": "PiCture eXchange",
    "apng": "Animated Portable Network Graphics",
    "png": "Portable Network Graphics",
    "pbm": "Portable Bitmap",
    "pgm": "Portable Graymap",
    "pnm": "Portable aNy Map",
    "ppm": "Portable Pixmap",
    "bw": "SGI Black and White",
    "rgb": "SGI RGB Image",
    "rgba": "SGI RGB Image with Alpha Channel",
    "sgi": "Silicon Graphics Image",
    "icb": "Truevision Targa Image",
    "tga": "Truevision TGA Image",
    "vda": "Truevision Targa Image",
    "vst": "Truevision Targa Image",
    "tif": "Tagged Image File Format",
    "tiff": "Tagged Image File Format",
    "webp": "WebP image",
    "emf": "Windows Enhanced Metafile",
    "wmf": "Windows Metafile",
    "xbm": "X BitMap",
}
OUTPUT_FORMATS_CHOICES = [(key, value) for key, value in OUTPUT_FORMATS.items()]

COLOR_MODES = {
    "blp": "RGB",
    "bmp": "RGB",
    "bufr": "RGB",
    "dds": "RGBA",
    "dib": "RGBA",
    "eps": "RGB",
    "ps": "RGB",
    "grib": "RGB",
    "h5": "RGB",
    "hdf": "RGB",
    "icns": "RGBA",
    "ico": "RGBA",
    "im": "RGB",
    "imt": "RGB",
    "jfif": "RGB",
    "jpe": "RGB",
    "jpeg": "RGB",
    "jpg": "RGB",
    "j2c": "RGB",
    "j2k": "RGB",
    "jp2": "RGB",
    "jpc": "RGB",
    "jpf": "RGB",
    "jpx": "RGB",
    "msp": "1",
    "pcx": "RGB",
    "apng": "RGBA",
    "png": "RGBA",
    "pbm": "RGBA",
    "pgm": "RGBA",
    "pnm": "RGBA",
    "ppm": "RGB",
    "bw": "L",
    "rgb": "RGB",
    "rgba": "RGBA",
    "sgi": "RGBA",
    "icb": "RGB",
    "tga": "RGBA",
    "vda": "RGB",
    "vda": "RGB",
    "vst": "RGB",
    "tif": "RGB",
    "tiff": "RGB",
    "webp": "RGBA",
    "emf": "RGB",
    "wmf": "RGB",
    "xbm": "L",
}
