from core.constants import IMAGE_INPUT_FORMATS, IMAGE_OUTPUT_FORMATS

INPUT_FORMATS_CHOICES = [(key, value) for key, value in IMAGE_INPUT_FORMATS.items()]
OUTPUT_FORMATS_CHOICES = [(key, value) for key, value in IMAGE_OUTPUT_FORMATS.items()]

COLOR_MODES = {
    "bmp": "RGB",
    "dcx": "RGBA",
    "dds": "RGBA",
    "dib": "RGBA",
    "flc": "RGBA",
    "eps": "RGB",
    "ps": "RGB",
    "grib": "RGB",
    "h5": "RGB",
    "hdf": "RGB",
    "icns": "RGBA",
    "ico": "RGBA",
    "im": "RGB",
    "imt": "RGB",
    "jfif": "RGB",
    "jpe": "RGB",
    "jpeg": "RGB",
    "jpg": "RGB",
    "j2c": "RGB",
    "j2k": "RGB",
    "jp2": "RGB",
    "jpc": "RGB",
    "jpf": "RGB",
    "jpx": "RGB",
    "msp": "1",
    "pcx": "RGB",
    "apng": "RGBA",
    "png": "RGBA",
    "pbm": "RGBA",
    "pgm": "RGBA",
    "pnm": "RGBA",
    "ppm": "RGB",
    "bw": "L",
    "rgb": "RGB",
    "rgba": "RGBA",
    "sgi": "RGBA",
    "icb": "RGB",
    "tga": "RGBA",
    "vda": "RGB",
    "vda": "RGB",
    "vst": "RGB",
    "tif": "RGB",
    "tiff": "RGB",
    "webp": "RGBA",
    "emf": "RGB",
    "wmf": "RGB",
    "xbm": "1",
    "xpm": "RGBA"
}
