# Generated by Django 4.2.3 on 2023-08-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipboard',
            name='auto_delete',
            field=models.BooleanField(default=True, help_text='Whether the media will be deleted after some time', verbose_name='Auto delete flag'),
        ),
        migrations.AlterField(
            model_name='clipboard',
            name='name',
            field=models.CharField(help_text='Name of the clipboard', max_length=32, verbose_name='Name'),
        ),
    ]
