# Generated by Django 4.2.3 on 2023-08-03 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0002_clipboard_auto_delete_alter_clipboard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipboard',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date the clipboard was created at', verbose_name='Creation date'),
        ),
    ]
