# Generated by Django 4.2.3 on 2023-08-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0003_alter_clipboard_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipboard',
            name='name',
            field=models.CharField(help_text='Name of the clipboard', max_length=256, verbose_name='Name'),
        ),
    ]
